# Deep neural network 만들기

## keras.Sequential
실제 Keras를 사용할때 이전 챕터에서 배웠던 Dense Layer 단독으로 사용되지 않고, Sequential이라는 클래스와 함께 사용된다.  
Keras의 Sequential 모델은 간단한 순차적인 신경망 구조를 구축하는 데 사용되는 클래스입니다.  
이 모델은 레이어를 순차적으로 쌓아 나가는 방식으로 만들어지며, 입력 데이터가 한 방향으로만 흐르는 구조를 가집니다.

In [5]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Sequential 모델 생성
model = Sequential()

# 입력 레이어와 은닉 레이어 추가
model.add(Dense(1, activation='relu', input_dim=5)) # 입력-출력

# 모델 요약 출력
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 6         
                                                                 
Total params: 6
Trainable params: 6
Non-trainable params: 0
_________________________________________________________________


In [2]:
import numpy as np
X = np.random.rand(1,5)
X

array([[0.37406582, 0.81802114, 0.23941548, 0.45026807, 0.28016624]])

In [6]:
model(X)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.689671]], dtype=float32)>

## keras.Sequential에 층 추가하기

In [8]:
X = np.random.rand(1,5)
X

array([[0.21576094, 0.94725864, 0.04155773, 0.83458016, 0.63665143]])

In [7]:
# Sequential 모델 생성
model = Sequential()

# 레이어 추가
model.add(Dense(3, activation='sigmoid', input_dim=5))  # 입력 레이어 5->3
model.add(Dense(1, activation='sigmoid'))  # 은닉 레이어 3->1

# 모델 요약 출력
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 3)                 18        
                                                                 
 dense_3 (Dense)             (None, 1)                 4         
                                                                 
Total params: 22
Trainable params: 22
Non-trainable params: 0
_________________________________________________________________


In [9]:
model(X)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.52340627]], dtype=float32)>

## 딥 뉴럴 네트워크

In [10]:
# Sequential 모델 생성
model = Sequential()

# 레이어 추가
model.add(Dense(10, activation='sigmoid', input_dim=5))  # 입력 레이어
model.add(Dense(5, activation='sigmoid'))  # 은닉 레이어
model.add(Dense(3, activation='sigmoid'))  # 은닉 레이어
model.add(Dense(5, activation='sigmoid'))  # 은닉 레이어

# 모델 요약 출력
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 10)                60        
                                                                 
 dense_5 (Dense)             (None, 5)                 55        
                                                                 
 dense_6 (Dense)             (None, 3)                 18        
                                                                 
 dense_7 (Dense)             (None, 5)                 20        
                                                                 
Total params: 153
Trainable params: 153
Non-trainable params: 0
_________________________________________________________________


In [11]:
model(X)

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[0.5666869, 0.5192662, 0.4893526, 0.5496288, 0.5347053]],
      dtype=float32)>