## List를 이용한 벡터의 표현

파이썬에서 숫자로 구성된 벡터를 다룰 수 있는 기본적인 자료형은 리스트이다.

In [1]:
# 패키지 불러오기
import numpy as np

In [9]:
# 리스트
x = [1, 3, 5, 7, 9]
print(x) # x의 값 출력
print(type(x)) # x의 타입 출력

[1, 3, 5, 7, 9]
<class 'list'>


In [3]:
# 리스트로는 벡터 연산할 수 없음
x + 3 # x의 모든 값에 일괄적으로 3을 더하고 싶었다.

TypeError: can only concatenate list (not "int") to list

In [4]:
# 리스트로는 벡터연산 할 수 없음
x + x # 두개의 벡터값을 더하고 싶었다.

[1, 3, 5, 7, 9, 1, 3, 5, 7, 9]

## Numpy Array를 이용한 벡터의 표현

NumPy는 파이썬에서 수치 계산과 데이터 분석을 위한 핵심 라이브러리 중 하나로, "Numerical Python"의 약어이다.  
NumPy는 다차원 배열(또는 행렬)을 효율적으로 다루는 기능을 제공하며, 이러한 배열을 사용하여 다양한 수학적 연산을 수행할 수 있다.

In [6]:
# numpy array로 변환
a = np.array(x)
a

array([1, 3, 5, 7, 9])

In [8]:
type(a)

numpy.ndarray

## Numpy Array를 이용한 벡터연산

숫자가 numpy array로 표현되면 그때부터는 벡터의 연산이 가능해진다.  
또한 속도도 매우 빠르다.

In [11]:
print(a+3)
print(a*3)
print(a/10)
print(a-3)

[ 4  6  8 10 12]
[ 3  9 15 21 27]
[0.1 0.3 0.5 0.7 0.9]
[-2  0  2  4  6]


In [13]:
b = np.array([2,4,6,8,10])
print(a+b)
print(a-b)
print(a/b)
print(a*b)

[ 3  7 11 15 19]
[-1 -1 -1 -1 -1]
[0.5        0.75       0.83333333 0.875      0.9       ]
[ 2 12 30 56 90]


## 리스트를 이용한 행렬(2차원 데이터의) 표현

우리가 생각해 볼 수 있는 2차원 데이터의 예시는 다음과 같다.
* 표 데이터: 엑셀 스프레드시트나 데이터베이스의 테이블과 같이 행과 열로 구성된 데이터는 2차원 데이터의 예시이다.  
  각 행은 레코드나 관측치를 나타내며, 각 열은 해당 관측치의 속성이나 변수를 나타낸다.  
  즉 1차원 벡터가 여러개 모였다고 생각하면 쉬울 것이다.
* 이미지 데이터: 흑백 이미지는 픽셀 값을 가로와 세로 위치로 나타내는 2차원 데이터이다.  
  각 픽셀은 밝기 값을 나타내며, 전체 이미지는 2차원 배열로 표현된다.  
  이미지 데이터포인트 한개를 표현하는데 2차원 데이터가 필요한 상황이다.

In [19]:
# 리스트로 2차원 데이터를 표현하는 방법은 다음과 같이 2차원 리스트를 만드는 것이다.
x = [[1,2,3],[4,5,6]]
print(x)

[[1, 2, 3], [4, 5, 6]]


In [20]:
print(x[0])
print(x[1])

[1, 2, 3]
[4, 5, 6]


In [17]:
print(x[0][0])

1


## Numpy를 이용한 행렬의 표현

마찬가지로 2차원 리스트로 표현된 벡터는 사칙연산이 어려우므로 numpy 배열로 바꾸어 표현하는 것이 좋다.

In [21]:
a = np.array(m)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a

array([[1, 2, 3],
       [4, 5, 6]])

## Numpy를 이용한 행렬의 벡터연산

In [24]:
print(a+3)
print(a/3)

[[4 5 6]
 [7 8 9]]
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]]


In [25]:
print(a+a)

[[ 2  4  6]
 [ 8 10 12]]


In [26]:
print(a/a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
# 추가적으로 numpy는 matrix의 곱 연산등 다양한 선형대수의 기능을 제공한다.
b = np.array([[2,4],[1,3],[2,4]])
np.matmul(a,b) # a와 b의 행렬연산

array([[10, 22],
       [25, 55]])

## 3차원 데이터는 무엇일까?
같은 행과 열로 구성된 (행렬)이 여러개 있다면 이를 3차원 데이터라고 볼 수 있다.

* RGB 이미지 데이터: 컬러 이미지는 가로, 세로 픽셀 위치와 각 픽셀에서의 빨강(R), 초록(G), 파랑(B) 색상 성분을 나타내는 3차원 데이터입니다.  
  이미지의 각 픽셀은 3개의 값을 가지며, 전체 이미지는 3차원 배열로 표현됩니다.  
  즉 데이터포인트 1개가 3차원으로 표현되는 상황이다.

In [31]:
a = np.array([[[1,2,3],[4,5,6]],[[2,4,6],[1,3,5]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 4, 6],
        [1, 3, 5]]])

## 배열의 차원과 크기확인

In [32]:
# ndim 차원확인
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)  # 출력: 2 (2차원 배열)

2


In [33]:
# shape 차원별 크기 확인
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # 출력: (2, 3) (2행 3열의 배열)

(2, 3)


## 배열의 모양 바꾸기

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr.shape

(2, 3)

In [38]:
arr.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
arr.reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])

In [40]:
arr.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [42]:
arr.reshape((3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])